### ISSUE TITLE
AttributeError: 'module' object has no attribute 'set_id_namespace'

### ISSUE THREAD

**Issue by vineetabajaj** [MAECProject/pefile-to-maec#8]
I am tring to execute pefile_to_maec. 
getting error "AttributeError: 'module' object has no attribute 'set_id_namespace'" in pefile_parser.py... 
Can anyone help from where to get the set_id_namespace(NS) function in maec utils..

![snapshot](https://cloud.githubusercontent.com/assets/26162225/23547207/652a7558-0028-11e7-8906-38e2fb711a8a.png)

**Comment by ikiril01** [comment]
Looks like you're missing the required`python-cybox` library. If you have pip installed, you can install it with the following command:

`pip install cybox==2.1.0.9`

If you don't have pip, you can download the package here and try to install it yourself (using setup.py): https://pypi.python.org/pypi/cybox/2.1.0.9

**Comment by gtback** [comment]
@ikiril01: Does pefile-to-maec not work with the newer (mixbox) versions of python-cybox? If so, we need to update the README, which currently says, `<= 2.2.0.0` (actually we need to update it anyway, since it should be `< 2.2.0.0` or really `cybox>=2.1.0.8,<2.1.1.0` as it says in setup.py).

**Comment by vineetabajaj** [comment]
sir, i have tried it in different versions and still getting the error.
Can you please help me in determining the exact versions on which
pefile_to_maec works?

**Comment by gtback** [comment]
Try with `cybox==2.1.0.12` and `maec==4.1.0.12`. See [here](https://github.com/MAECProject/pefile-to-maec/issues/9#issuecomment-284401862) for more information.

**Comment by vineetabajaj** [comment]
thanks for helping..

**Comment by gtback** [comment]
Happy to help! If there's anything else, feel free to open a new issue.
